10up/brightcove-video-connect

assets/js/src/tinymce.js
Found a lot of issues where bctiny.playlistEnabledPlayers[options.shortcode.attrs.named.account_id] is false rather than an array of player IDs. wp cache flush cleans this up, however I wasn't able to find the root cause of the issue.
This fix falls back to the default player if we can't find one to avoid not rendering the playlist in tinymce.
=> Fallback to default player for playlist rendering

includes/api/class-bc-text-track.php
Have tested text track uploads since adding the param, all seems to be normal.
Resolves feedback we got on 1.2.1 from VIP.
=> Add strict parameter to in_array

includes/admin/class-bc-admin-settings-page.php, includes/admin/class-bc-admin-sources.php
Changed Button text to ready 'Add Brightcove Account'. Change title on next screen to match new button name
=> Label Change from Add Source to Add Brightcove Account

includes/class-bc-setup.php
At this point we are on the page that we need to be on and the message is not needed.
=> Restrict admin notice on Sources Edit Page

includes/admin/class-bc-templates.php, includes/api/class-bc-player-management-api.php, includes/class-bc-accounts.php, includes/class-bc-setup.php
When changing from one account to the other when embeding a video to a post, the video players don't change. The video players used for one account will not work on other accounts. So, I made a change to account for all account players.
Please let me know if you see anything wrong in that or if you see a way to do it more efficiently.
Thank you.
=> Add support for all account players when embeding videos

brightcove-video-connect.php, includes/admin/class-bc-status-warning.php
Towards #53 
Skips BC status checks on ajax requests, and checks for/stores in cache the results of the remote request.
=> Limit BC Status Checks

includes/api/class-bc-player-management-api.php
Looks like this new function got added with my last PR in hopes to modify the list of players in the media modal. https://github.com/10up/brightcove-video-connect/pull/63
https://github.com/10up/brightcove-video-connect/commit/47e60cb677a18e2149039cb6e9d89590a6a8f60f
Adding a filter here on the new function.
=> filter for all players based on account

includes/api/class-bc-cms-api.php
Removing "counts" from the endpoint restores functionality; have not found documentation from Brightcove noting this change.
=> Fix broken video_get_sources method.

includes/api/class-bc-api.php
VIP Go helper function includes a default 1s timeout. In the plugin, a timeout from Wordpress produces an empty response, which can manifest as a blank Videos grid.
Increasing timeout from 1s to 3s for vip_safe_wp_remote_get allows for more time for the API response, resolving the above issue in testing.
=> Increase timeout

includes/class-bc-setup.php
The button will appear on all editors (advanced custom fields, carbon fields) but the plugin is setup to only work with the main editor
=> Only show button to main content editor

includes/class-bc-setup.php
Since the delete_option performs always at least one SQL query in order to figure out whether the option exists, we can save one database query by checking whether the option even exists before attempting
to delete it.
In case of the WordPress.com platform, such a check can even prevent alloptions cache flush which happens when the `delete_option` is called.
See https://developer.wordpress.org/reference/functions/delete_option/ for more details.
We have already deployed this patch to production on the WordPress.com platform, since it has been causing issues for certain sites hosted in there.
Let me know if you have any questions.
=> Check if option exists before attempting to delete it

includes/api/class-bc-api.php, includes/api/class-bc-cms-api.php
Search function was not producing the same results as in Brightcove Studio. With two word searches, the same results would come whether it was formatted `word word`, `word+word`, or `"word word"`. This fix addresses that.
=> search in line with brightcove studio search

includes/class-bc-setup.php
In WP 4.9 Flash and Silverlight is no longer supported, see https://core.trac.wordpress.org/ticket/41755#no0 for more details.
=> Remove the deprecated options from Plupload

includes/api/class-bc-cms-api.php
**Issue:** PHP notices thrown on post list and post edit screens when no BC account information available.
**To reproduce:**
* Install the latest stable WordPress version.
* Make sure `WP_DEBUG` is `true`.
* Activate the latest stable version of this plugin.
* Navigate to Posts > All posts.
* Observe PHP Notices being displayed.
* Navigate to New post screen.
* Observe PHP Notices being displayed.
**Fix:**
* In the `fetch_folders` method, make sure `$request` resolves to non-error value (not `false`, not `WP_Error` instance).
=> Fix: Check for valid API response before accessing it

.github/workflows/push-asset-readme-update.yml, .github/workflows/push-deploy.yml
This adds the GitHub Actions to help automate the deploy to WordPress.org for plugin releases as well as readme.txt and asset updates.
none
Eliminates hassle and time needed to work with .ORG's SVN.  Just work in Git, sit back, and enjoy.
none identified.
Resolves #133.
n/a
=> Add GitHub Actions for WordPress.org deployments

includes/class-bc-permissions.php
This adds a check of the `editor` role capabilities and splits out the addition of the capabilities into separate functions.
If the `editor` role somehow gets reset to base capabilities, it will never receive the brightcove caps again since the `administrator` role still contains the correct capabilities.
Adding a check of the `editor` role, and adding the role capabilities individually ensures that each role will get reassigned necessary capabilities if they are ever lost for any reason.
Fixes #110
=> Check each role for presence of capability

includes/api/class-bc-player-management-api2.php
We had an issue where API credentials were revoked and it caused a fatal error on our site. This error originated in the code that gets a list of all available players. The request to get the players will fail and we have a `is_wp_error` check on that but we don't check for that until after we try and use the returned value (which causes fatals if that value is an error).
This PR moves that check up prior to us trying to use that value and also adds a check to ensure the returned value isn't `false`.
None
Prevent fatal errors if API credentials are revoked.
None
This fix was pushed into our staging environment that was experiencing the fatal errors and this resolved those
=> Prevent a fatal error when API request fails

CHANGELOG.md, brightcove-video-connect.php, languages/brightcove.pot, readme.txt
This PR updates the README and plugin version for the 2.1 release.
=> 2.1 Release

includes/admin/class-bc-admin-labels-page.php
Replaces HTML attribute escaping function with `esc_attr()` in stead of `esc_html()`
=> Escape HTML attribute by esc_attr()

includes/api/class-bc-cms-api.php
Prevents PHPCS warning: `Variable $data is undefined (VariableAnalysis.CodeAnalysis.VariableAnalysis.UndefinedVariable)`
=> Minor refactor to definition of $data array

includes/admin/class-bc-admin-sources.php
This change fixes the Default Source field when is submitted unchecked.
1. Go to Brightcove -> Settings and edit a source
2. Check the field Default Source and save
3. Uncheck the field Default Source, save and see if the field is unchecked after form submission
Fixed Default Source field when is submitted unchecked.
=> Fix Default Source field when is submitted unchecked

assets/js/src/block.js, assets/js/src/tinymce.js, includes/class-bc-setup.php, includes/class-bc-utility.php
When the user adds a playlist in the editor, the playlist is rendered using a video player. This change fixes the playlist preview to use a playlist player. 
1. Add the Brightcove block and add a playlist
2. Check if the player utilized is a playlist player
Fixed playlist preview in the editor
=> Fix playlist preview in the editor

includes/class-bc-utility.php
Fixed a typo in global keyword `$allowedtags`.
n/a
Content in admin notices will be escaped properly.
None.
I was type-hinting the `apply_filters( 'wp_kses_allowed_html', $context, 'explicit' );` filter to accept `string|array` and PHP did throw a Fatal Error because of this typo. 
Fixing the typo also fixed this error.
See https://developer.wordpress.org/reference/functions/wp_kses_allowed_html/#source
n/a
Fix: Fix typo for the `$allowedtags` global used in conjunction with `wp_kses`
=> Fix typo for the allowed tags global.

includes/class-bc-playlist-shortcode.php, includes/class-bc-utility.php, includes/class-bc-video-shortcode.php
This PR fixes responsiveness issues with the Brightcove players. The following players should be now responsive if the user has selected the option:
**Video player:**
* Javascript/responsive
* Iframe/responsive
**Playlist player:**
* Iframe/responsive
**Video experience player:**
* Javascript/responsive 
**Playlist experience player:**
* Javascript/responsive
Props @
=> Pass sizing attribute to determine if responsiveness should be enabled

includes/class-bc-setup.php
In WordPress 5.5, the type `int` is not one of the built-in types supported by WordPress. Since we're dealing with attributes in HTML the values are stored as strings and that way this PR changes the type from `int` to `string`
References:
- https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/#attribute-source
WordPress will not throw a warning when debug mode is enabled.
Since `int` is not supported and the type falls back to `string`. So I believe we don’t need to make a kind of “migration” if we change to `string`.
It can be verified by looking at the posts that have a video embedded and creating a post and adding a Brightcove block.
Closes #172 
Fixed attributes type.
=> Update attribute type from int to string

includes/admin/class-bc-admin-menu.php
This PR fixes the fatal error below when array is `NULL`:
```
PHP message: PHP Fatal error:  Uncaught TypeError: array_shift(): Argument #1 ($array) must be of type array, null given in /var/www/wp-content/plugins/brightcove-video-connect/includes/admin/class-bc-admin-menu.php:40
Stack trace:
#0 /var/www/wp-content/plugins/brightcove-video-connect/includes/admin/class-bc-admin-menu.php(40): array_shift(NULL)
```
=> Fix fatal error when array is null

includes/class-bc-utility.php
* Fixes playsinline not working with iframe elements. 
* It also adds a new method to build a common src url needed for iframe and video-js elements https://github.com/10up/brightcove-video-connect/pull/313/files#diff-a7e290eaff3f36e927ee0bf922391369318ce128aa6daba790b4898e13451cb7R1525
=> Fixes playsinline not working with iframe elements

brightcove-video-connect.php, includes/class-bc-setup.php, includes/class-bc-utility.php
This PR checks if the Brightcove accounts have been set, and if they are not, it prevents loading code that doesn't make sense to be loaded before.
The fix specifically targets #198 and #231 where remote requests are being fired. It doesn't make sense to fire these if the plugin has not been configured with a valid Brightcove Account first. 
It also solves a bug related to the account data when we do not have that yet. 
Closes #198 
Closes #231
> Fixed -  Prevent API calls when Brightcove has not been configured yet
Props @oscarssanchez
=> Bugfix:  Prevent API calls when Brightcove has not been configured yet

assets/js/brightcove-admin.js, assets/js/src/views/media-details.js
This PR updates the name of the embed type variable to "in page". It used to be called javascript but at some point we changed that name. By updating it we are solving a bug where embed types where losing customization options in the Brightcove media modal.
> Fixed - Customization options hidden when switching embed type in in-page experiences.
Props @oscarssanchez, @felipeelia
=> Update name of embed type

assets/js/src/block.js
Closes #334
Closes #335
Closes #336
> Changed - Use wp.blockEditor.BlockControls if available
Props @felipeelia and @oscarssanchez
=> Compatibility with WP 6.2+ JS

assets/js/src/views/media-details.js
This PR fixes an issue where the playlists have empty "Created At:" and "Updated At:"
Closes #347 
Click on the playlist and check if "Created At:" and "Updated At:" are not empty
> Fixed - Playlists have empty "Created At:" and "Updated At:"
Props @burhandodhy @felipeelia
=> Fix: Playlists have empty "Created At:" and "Updated At:"

assets/js/src/views/toolbar.js
This PR fixes an issue where the help notice being displayed more than once. 
Closes #344
> Fixed - Help notices being displayed more than once
Props @burhandodhy @felipeelia
=> Fix: Help notices being displayed more than once

includes/admin/api/class-bc-admin-media-api.php, includes/api/class-bc-text-track.php
This PR fixes an issue where the caption was not uploading in the brightcove. 
Closes #
- Upload the caption for the video
- Make sure it ends successfully
> Fixed - Caption upload issue
Props @burhandodhy @felipeelia
=> Fix caption upload issue

assets/js/src/models/media-collection.js
This PR fixes an issue where the plugin displays the error message when the new filter is applied before the previous ajax is completed. 
Closes #355
1. Go to the video page.
2. Apply the filters in such a way that you apply the second filter before the ajax request for the first filter is completed.
3. Unselect all the filters.
> Fixed - Display error message when the previous request is aborted
=> Don't trigger fetch:apiError if request is aborted

assets/js/src/views/media-details.js, includes/admin/class-bc-templates.php
Closes #345
1. Clicking on a video and then on "Edit" open the video details to be edited. The only way to go back is to scroll down to the bottom and click "Back". Hitting "Back" on the browser or reloading the page has an unexpected behavior.
2. Clicking on "Edit" on an Inactive video goes to a blank page.
https://github.com/10up/brightcove-video-connect/assets/184628/63f2ae23-c047-4016-9dca-ea13f0db0e78
> Fixed - Clicking on the "Edit" and "Preview"  buttons for the inactive videos breakes the layout
Props @burhandodhy @felipeelia
=> Fix: Don't open the detailed view if button is disabled

includes/class-bc-utility.php, includes/sync/class-bc-videos.php
This PR fixes an issue where the special characters get encoded due to the `utf8_uri_encode` function in `sanitize_payload_item` and `sanitize_payload_args_recursive` functions.
Closes #348 
1. Upload or edit a Brightcove video
2. Use a special character in the Name field such as ’, —, or é.
3. Reload the page and confirm the field doesn't have encoded characters anymore
> Fixed - Add support for special characters
Props @burhandodhy @cr0ybot
=> Fix: Add support for special characters

includes/class-bc-labels.php
This PR fixes an issue where the  'Label added' message is displayed even when the label fields are empty. 
Closes #356 
1. Go to the "Labels" page
2. Submit the form without filling in the data
3. The plugin will show the "Label added" notice
> Fixed - Don't show 'Label added' message if label data is empty
=> Fix: Don't show 'Label added' message if label data is empty

includes/admin/api/class-bc-admin-media-api.php
This PR fixes an issue where the plugin throws a warning while saving the video.
Closes #354 
- Go to the videos page
- Edit a video
- Click on Save
- It should save the video without any errors or notices
> Fixed - PHP warning while saving a video
Props @MARQAS , @felipeelia
=> Fix: Undefined array key sub_type

includes/admin/class-bc-admin-labels-page.php
This PR fixes an issue where the plugin throws a warning in the label field while editing a label
Closes #357 
1. Go to the Labels page
2. Click on Edit label
3. It should display the label value
> Fixed - PHP warning while editing a label
Props @MARQAS , @felipeelia
=> Fix: Only variables should be passed by reference

includes/class-bc-setup.php
This PR fixes the issue where the plugin sends unwanted API calls on all the admin pages.
Closes #
> Fixed - Limit API calls on unwanted admin pages.
=> Send API requests only on the required pages

includes/api/class-bc-api.php, includes/api/class-bc-player-management-api2.php, includes/class-bc-setup.php, includes/class-bc-utility.php
This PR cache the API response even when the API returns the error 
Closes #367
> Changed - Cache the API response and display a message from where use can retry the API again. 
Props @burhandodhy @jonnynews
=> Cache the Api response

assets/js/src/views/video-edit.js, includes/admin/api/class-bc-admin-media-api.php
This PR fixes an issue where the update call fails when the labels are empty. Previously, when labels were empty, the payload had an array an one empty index
Closes #
> Fixed - Video update API fails when labels are empty
=> Fix: Update call fail when labels are empty

includes/class-bc-setup.php
Taken from: https://github.com/10up/brightcove-video-connect/pull/388
Ensure that the get_current_screen is not null. Also check is the base is "post" and not the id. If ID can be set to "page" or "article" for custom post types. So this check for $current_screen->id === 'post' is invalid.
The conditional statements in class-bc-setup.php have been updated to improve fetching folders and players. The revised conditions not only check for user permission and page type, but they also ensure that the $current_page variable is defined before attempting to access its properties. This adds an extra layer of validation to prevent potential errors.
Closes https://github.com/10up/brightcove-video-connect/issues/387
> Fixed - Cannot use Brightcove block on custom post types.
Props @spacedmonkey, …
=> Update condition for fetching folders and players

assets/js/src/block.js
From #386
Fix the typo in assets/js/src/block.js that causes Block Recovery to be displayed on reload of a new block in a post.
Closes #
385
> Fixed - Typo when saving the language_detection attribute
Props @claimableperc
=> Fix typo in language_detection attribute.

includes/class-bc-utility.php
This PR adds a missing `script` closing tag.
Closes #
Adds a playlist with "JavaScript Vertical" style
Check on the frontend its rendering correctly.
> Fixed - Add missing `script` closing tag.
=> Fix: Add missing script close tag

assets/js/src/block.js, assets/js/src/views/media-details.js, includes/class-bc-in-page-experience-shortcode.php, includes/class-bc-utility.php
This PR fixes the issue where the video width and height is different as compare to frontend.
Closes #
> Fixed - Video appearance in the editor
=> Fix: Single Video Player Embed appears very different in the block editor

assets/js/src/views/video-edit.js
Closes #
> Changed - Only show jpg and png images in the media modal
=> Allow only png and jpg images for thumbnail and poster

assets/js/src/views/media-details.js, includes/class-bc-utility.php
Closes #
> Fixed - Calculate the padding based on the Aspect ratio
=> Calculate height dynamically

assets/js/src/views/video-edit.js, includes/admin/api/class-bc-admin-media-api.php
This PR fixes an issue where the save history function isn't working at all.
Closes #
> Fixed - Video Save History
=> Fix: Save history isn't working

assets/js/src/views/toolbar.js
This PR hides the search field if the video folder is selected/
Closes #
> Changed - Hide search field if video folder is selected.
=> Hide search field if video folder is selected

assets/css/brightcove_playlist.css, assets/css/components/colors.css, assets/css/components/modals.css, assets/css/components/playlists.css, assets/css/components/uploads.css, assets/css/components/video-edit.css, assets/css/components/video-grid.css, assets/css/components/video-page.css
This PR fixes the CSS linting issues.
Closes #
> Developer - Fix CSS linting issues
=> Fix: CSS linting issues
