- includes/class-bc-utility.php
> Add avi to list of accepted MIMEtypes

- includes/admin/class-bc-admin-videos-page.php
- includes/admin/class-bc-status-warning.php
- includes/admin/class-bc-templates.php
- includes/api/class-bc-api.php
- includes/class-bc-accounts.php
- includes/class-bc-utility.php
- languages/brightcove.pot
I went over all the PHP files and replaced hardcoded strings with translation function.
> Remove hardcoded strings

- includes/admin/class-bc-admin-sources.php
Updated notice new application help text. External links added to assist in registering a new application
> Updated notice new application help text.

- includes/api/class-bc-player-management-api.php
Would like the player list to be filterable. Desire to be able to control the list of players that may be displayed within the video connect modal in the article edit screen (nice to not display and test/development players).
> filter player list api response

- composer.json
- deploy.sh
Please add to packagist.org too
> Add composer.json file

- assets/js/src/tinymce.js
- includes/class-bc-setup.php
This fixes both https://github.com/10up/brightcove-video-connect/pull/71 which I accidentally closed a while ago and it also fixes #74
> Dynamic Player ID

- includes/api/class-bc-cms-api.php
This PR adds escaping of the API URL.
> URL escaping

- includes/api/class-bc-cms-api.php
Do not merge until #101 is approved.
> URL escaping (Master)

- assets/js/brightcove-admin.js
Change is only in main code, not minified code. I was unsure if that was a change I make myself, or if it's something done on your end when code is deployed.
> Search with enter

- README.md
- readme.txt
related task: https://tenup.teamwork.com/#tasks/18602261
> Bump/tested up to 5.2

- includes/api/class-bc-player-management-api2.php
> Do not send data from inactive players to the plugin

- includes/admin/api/class-bc-admin-media-api.php
Updated padding-top to 56.25% to match embed code generated by Video Cloud Studio to ensure parity and avoid black lines around player.
> Updated padding-top to 56.25%

- includes/api/class-bc-player-management-api2.php
- includes/class-bc-utility.php
This PR changes the default player order coming from the connector API and sorts it by most recently updated to the oldest, to better resemble the behavior on Brightcove Studio.
> Order players from most recent updated to oldest

- includes/admin/class-bc-admin-settings-page.php
- includes/admin/class-bc-templates.php
Sets a default settings field to set size of players
Registers a settings group for default player settings.
This PR Adds a new field in the settings menu to add a default player size per discussion on #129 
Resolves #129
> Feature default player size

- includes/api/class-bc-cms-api.php
Fixes bug that causes a WordPress error notice when a video contains special characters in its title.
> url encode special characters

- includes/admin/class-bc-admin-settings-page.php
> Use correct escaping function

- includes/admin/class-bc-admin-settings-page.php
> Clarify width needs to be in pixel units

- README.md
`readme.txt` was updated in v1.8 to note the WordPress "tested up to" version of 5.3.  This PR updates the `README.md` file accordingly.
n/a
Ensures we're consistent in describing our WP tested-up-to version.
None identified.
Manually verified via the GitHub web UI.
Relates to #138 
n/a
> Update WP version in docs

- includes/class-bc-accounts.php
> Fixes validation for playlist when adding a new account

- README.md
- brightcove-video-connect.php
- readme.txt
> 1.8.1 release

- includes/api/class-bc-cms-api.php
> Remove url encoding as ingest API dont allow anymore

- README.md
- brightcove-video-connect.php
- readme.txt
> Release 1.8.2

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- readme.txt
> 1.9.0 Release

- assets/js/src/tinymce.js
> Fixes preview when switching from classic to gutenberg

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- readme.txt
1.9.1 Release
Adds the following:
* Bug in preview when switching from classic editor to Gutenberg.
* Bug with editor capabilities.
> Release 1.9.1

- brightcove-video-connect.php
- includes/class-bc-setup.php
If credentials are revoked on Brightcove Studio
display a notice to alert the user to update his
settings.
Without it, the user will not be able to use the connector.
This PR adds a notice if the Brightcove credentials are removed on Brightcove Studio, and they are not updated in the Brightcove plugin (causing the plugin to not be able to fetch for videos/playlists).
It prompts the user to enter their credentials in the settings page.
> Display error notice if credentials are revoked

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- readme.txt
> 1.9.2 Release

- includes/admin/api/class-bc-admin-media-api.php
Hi @felipeelia , could you please review this feature? It simply adds a new filter to set a default state to filter. implements #178 
implements #179 
Added a filter set to inactive and worked as expected.
> Add filter to define state default filtering

- includes/api/class-bc-cms-api.php
> Fixes WP error when activating plugin on fresh install

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- readme.txt
> 2.1.1 Release

- includes/admin/class-bc-templates.php
> Display default state filter value on select dropdown

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package.json
- readme.txt
This PR updates plugin version, README and POT file in order to prepare for 2.1.2 release.
> Release 2.1.2

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package.json
- readme.txt
> 2.1.3 release

- assets/js/src/block.js
- includes/class-bc-setup.php
> Add missing mute attribute in the block

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package.json
- readme.txt
> Bump version to 2.1.4

- brightcove-video-connect.php
- includes/admin/api/class-bc-admin-media-api.php
- includes/api/class-bc-api.php
- includes/api/class-bc-oauth.php
- includes/class-bc-labels.php
- includes/class-bc-utility.php
This change removes the logic to use the bc_transient_keys option.
Fixed performance issue related with bc_transient_keys option
> Remove bc_transient_keys option

- includes/admin/class-bc-admin-labels-page.php
- includes/admin/class-bc-admin-settings-page.php
Fixes these warnings:
```php
PHP Notice:  Undefined index: account in /var/www/html/wp-content/plugins/brightcove-video-connect/includes/admin/class-bc-admin-settings-page.php on line 26
PHP Stack trace:
PHP   1. {main}() /var/www/html/wp/wp-admin/post.php:0
PHP   2. require_once() /var/www/html/wp/wp-admin/post.php:12
PHP   3. do_action() /var/www/html/wp/wp-admin/admin.php:175
PHP   4. WP_Hook->do_action() /var/www/html/wp/wp-includes/plugin.php:478
PHP   5. WP_Hook->apply_filters() /var/www/html/wp/wp-includes/class-wp-hook.php:311
PHP   6. BC_Admin_Settings_Page->delete_source() /var/www/html/wp/wp-includes/class-wp-hook.php:287
```
```php
[PHP Notice:  Undefined index: refresh_labels in /var/www/html/wp-content/plugins/brightcove-video-connect/includes/admin/class-bc-admin-labels-page …
```
> Fix undefined index warnings

- includes/class-bc-labels.php
- includes/class-bc-utility.php
This change fixes an issue when the bc_transient_version value is incremented.
> Fix delete all caches issue

- CHANGELOG.md
- README.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package.json
- readme.txt
> Prepare Release/2.2.0

- readme.txt
> Update contributors in readme.txt

- README.md
> Fix screenshots extension in README.md

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package-lock.json
- package.json
- readme.txt
> Prepare Release/2.2.1

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package-lock.json
- package.json
- readme.txt
> Prepare Release/2.3.1

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package-lock.json
- package.json
- readme.txt
> Prepare Release/2.4.0

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package-lock.json
- package.json
- readme.txt
> Prepare Release/2.5.0

- readme.txt
> Change stable tag

- composer.json
- includes/admin/api/class-bc-admin-media-api.php
- includes/admin/class-bc-templates.php
- includes/api/class-bc-cms-api.php
- includes/class-bc-labels.php
- includes/class-bc-setup.php
- includes/class-bc-utility.php
- includes/sync/class-bc-videos.php
This commit is a first step to bring the Brightcove plugin to better code standards by using automatic code lint/fix. There's still more errors detected by lint that should be addressed later on.
Props @
> phpcbf automatic fixes

- CHANGELOG.md
- README.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package-lock.json
- package.json
- readme.txt
> Release 2.7.0

- readme.txt
> Bump tested up to 6.0

- CHANGELOG.md
- brightcove-video-connect.php
- languages/brightcove.pot
- package.json
- readme.txt
> Release 2.8.1

- .distignore
Add a distignore file to be used in the deploy process.
> Add distignore file

- assets/js/src/block.js
- includes/admin/class-bc-templates.php
- includes/class-bc-utility.php
* Fixes bug with playlist experience not displaying correctly in frontend.
* Fixes bug with playlist rendering different display options
Closes #265 
> Fixed - playlist experience not rendering correctly. 
Props @oscarssanchez
> Bugfix: playlist experience not rendering correctly in frontend

- includes/api/class-bc-api.php
- includes/api/class-bc-oauth.php
- includes/class-bc-setup.php
Closes #
> Added - Brightcove version to user agent string
Props @felipeelia
> Add Brightcove version to user agent string

- readme.txt
> Update version in readme.txt

- assets/js/src/block.js
This PR fixes an issue where selecting multiple videos in a video experience results in an error.
Closes #
> Fixed - Selecting multiple videos in a video experience ends with an error. 
> Fix: Selecting multiple videos while embedding a Video Experience results in error

- assets/scss/components/_video-grid.scss
- includes/admin/class-bc-templates.php
- includes/api/class-bc-cms-api.php
This PRs adds the video folder name on top of thumbnail.
Closes #
> Added - Add folder name on top of video thumbnail.
> Add folder name on top of video thumbnail

- assets/css/admin.css
- assets/css/components/admin-dashboard.css
- assets/css/components/video-page.css
This PR fixes an alignment issue for the icon.
Closes #
> Fixed - Logo alignment issue
> Fix logo alignment
